# tetris-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: count-deployment
spec:
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: count
  template:
    metadata:
      labels:
        app: count
    spec:
      containers:
        - name: count
          image: prathvipp/click-game # Replace with the actual image tag
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listens on
